#!/usr/bin/env python2
import re
import urllib2
import sys

URL = 'http://www.lix.se/index.php'

def main():

  text = readInput()

  html = getLixResult(paddText(text))

  result = parseHtml(html)

  print(result)

def readInput():
  text = ""
  for line in sys.stdin:
    text += line
  return text
  
def paddText(text):
  return """------WebKitFormBoundaryoaMIB19RxdzFTEx3
Content-Disposition: form-data; name="data"

"""+text+"""

------WebKitFormBoundaryoaMIB19RxdzFTEx3
Content-Disposition: form-data; name="submit"

Analysera
------WebKitFormBoundaryoaMIB19RxdzFTEx3
Content-Disposition: form-data; name="f"


------WebKitFormBoundaryoaMIB19RxdzFTEx3--"""
  
def getPage(url, data):
  user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.91'
  content_type = "multipart/form-data; boundary=----WebKitFormBoundaryoaMIB19RxdzFTEx3"
  headers={'User-Agent': user_agent, 'Content-Type': content_type}
  request = urllib2.Request(url,data,headers)
  response = urllib2.urlopen(request)
  html = response.read()
  response.close()
  return html

def getLixResult(data):
  return getPage(URL, data)
  
def parseHtml(html):
  score = parseScore(html)

  return score

def parseScore(html):
  rg = re.compile('<b>(\d+)</b>')
  m = rg.search(html)
  if m:
    return int(m.group(1))
  return None

if __name__ == "__main__":
  main()
